import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { BackgroundContainer, MenuContainer } from "./styles";
import userImage from "../../../public/profile.jpg";
import background from "../../../public/background.jpg";
import premium from "../../../public/premium.svg";
import { BookmarkSimple } from "phosphor-react";
import { Plus } from "phosphor-react";
export function Menu() {
    return (_jsxs(MenuContainer, { children: [_jsxs("div", { className: "user-container", children: [_jsx(BackgroundContainer, { image: background }), _jsx("img", { src: userImage, alt: "", className: "image-container" }), _jsxs("div", { className: "name-office-container", children: [_jsx("div", { className: "name-container", children: _jsx("a", { href: "", children: "Carolina dos Santos Limeres" }) }), _jsx("div", { className: "office-container", children: "Front-End Developer" })] }), _jsxs("div", { className: "views-connections-container", children: [_jsxs("a", { href: "", className: "views-container", children: [_jsx("span", { className: "views", children: "Visualiza\u00E7\u00F5es do perfil" }), _jsx("span", { className: "number-container", children: "16" })] }), _jsxs("div", { className: "connections-container", children: [_jsxs("div", { className: "connections-network-container", children: [_jsx("span", { className: "connections", children: "Conex\u00F5es" }), _jsx("span", { className: "network", children: "Amplie sua rede" })] }), _jsx("span", { className: "number-container", children: "49" })] })] }), _jsx("div", { className: "premium-container", children: _jsxs("a", { href: "", className: "premium-link-container", children: [_jsx("p", { className: "leads", children: "Encontre leads de mais qualidade" }), _jsxs("div", { className: "text-icon-container", children: [_jsx("img", { src: premium, alt: "", className: "premium-image" }), _jsx("span", { className: "premium-text", children: "Experimente o Sales Navigator por EUR0" })] })] }) }), _jsxs("a", { href: "", className: "saved-container", children: [_jsx(BookmarkSimple, { size: 16, weight: "fill", className: "saved-icon" }), _jsx("span", { className: "saved-text", children: "Itens salvos" })] })] }), _jsxs("div", { className: "options-container", children: [_jsxs("div", { className: "list-container", children: [_jsx("div", { className: "groups-container", children: _jsx("a", { href: "", children: "Grupos" }) }), _jsxs("div", { className: "events-container", children: [_jsx("a", { href: "", className: "events", children: "Eventos" }), _jsx("a", { href: "", className: "plus-icon-container", children: _jsx(Plus, { size: 16, weight: "bold", className: "plus-icon" }) })] }), _jsx("div", { className: "hashtags-container", children: _jsx("a", { href: "", children: "Hashtags seguidas" }) })] }), _jsx("div", { className: "find-more-container", children: _jsx("a", { children: "Descubra mais" }) })] })] }));
}
